[project]
name = "Wall"
version = "0.1.0"
description = "Service to view interesting posts to users."
requires-python = ">=3.13"
dependencies = [
    "mypy>=1.19.1",
    "pydantic>=2.12.5",
    "ruff>=0.14.10",
]
